assets:
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  secring.gpg: yegor256/home#assets/secring.gpg
  pubring.gpg: yegor256/home#assets/pubring.gpg
install: |
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors -Dstyle.color=never
release:
  pre: false
  script: |-
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi -Dstyle.color=never --errors --settings ../settings.xml
    mvn clean site-deploy -Psite --errors --settings ../settings.xml
